apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  # name: bahmni-aws-ingress-class
  name: bahmni-nginx-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
spec:
  # controller: ingress.k8s.aws/alb
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bahmni-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: bahmni.k8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bahmni-web
                port:
                  number: 8091

          - path: /openmrs
            pathType: Prefix
            backend:
              service:
                name: openmrs
                port:
                  number: 8080

          - path: /lab
            pathType: Prefix
            backend:
              service:
                name: bahmni-lab
                port:
                  number: 8090
          - path: /document_images
            pathType: Prefix
            backend:
              service:
                name: document-server
                port:
                  number: 8099
          - path: /openmrs/auth
            pathType: Exact
            backend:
              service:
                name: document-server
                port:
                  number: 8099
          - path: /summary
            pathType: Exact
            backend:
              service:
                name: document-server
                port:
                  number: 8099
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: document-server
                port:
                  number: 8099
    - host: lab.bahmni.k8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bahmni-lab
                port:
                  number: 8090
    - host: patient-docs.bahmni.k8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: document-server
                port:
                  number: 8099
    - host: ef9f-122-169-1-37.ngrok.io
      http:
        paths:
          - path: /openmrs
            pathType: Prefix
            backend:
              service:
                name: openmrs
                port:
                  number: 8080
