apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: document-server
    environment: dev
  name: document-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: document-server
        environment: dev
    spec:
      containers:
        - image: document-server:local
          name: document-server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/nginx/html/document_images
              name: openmrs-document-images
      restartPolicy: Always
      volumes:
        - name: openmrs-document-images
          persistentVolumeClaim:
            claimName: openmrs-document-images-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: document-server
spec:
  ports:
    - name: '8099'
      port: 8099
      targetPort: 80
  selector:
    app: document-server
    environment: dev
  type: NodePort
